stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - src/load_data.py
    - src/get_data.py
    - data_given_by_client/card_transdata.csv
    outs:
    - data/raw/raw_data.csv

  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - src/split_data.py
    - src/get_data.py
    outs:
    - data/processed/train_data.csv
    - data/processed/test_data.csv


    