General:
  random_state: 43
  test_size: 0.3
  target_col: fraud

data_location:
  data_given_by_client: data_given_by_client/card_transdata.csv
  raw_data_path: data/raw/raw_data.csv
  train_data_path: data/processed/train_data.csv
  test_data_path: data/processed/test_data.csv
